name: model.ninateka.pl
# This package is not intended to be published
publish_to: none
description: >
  This package contains model classes to define Ninateka API data structures:
  https://ninateka.pl
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  meta:
  dart_json_mapper:
dev_dependencies:
  http:
  test:
  lints:
  build_runner: